# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='checking',
            field=models.BooleanField(default=True),
        ),
    ]
