# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 17:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_transaction_checking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='checking',
        ),
    ]
