# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-17 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_profile_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='deposit_or_debit',
            field=models.CharField(choices=[('w', 'withdrawl'), ('d', 'deposit')], default='w', max_length=7),
            preserve_default=False,
        ),
    ]
