# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-17 16:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_transaction_deposit_or_debit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='deposit_or_debit',
            new_name='withdrawl_or_deposit',
        ),
    ]
